let films = [
    {
        id: 1,
        filterGenre1: '',
        filterGenre2: '',
        picture: 'movie-1.png',
        alt: '',
        title: 'Movie 1',
        year: '',
        badge: '',
        duration: '',
        rating: '8.7',
    },
    {
        id: 2,
        filterGenre1: '',
        filterGenre2: '',
        picture: 'movie-2.png',
        alt: '',
        title: ' Movie 2',
        year: '',
        badge: '',
        duration: '',
        rating: '6.7',
    },
    {
        id: 3,
        filterGenre1: '',
        filterGenre2: '',
        picture: 'movie-3.png',
        alt: '',
        title: 'Movie 3',
        year: '',
        badge: '',
        duration: '',
        rating: '9.3',
    },
    {
        id: 4,
        filterGenre1: '',
        filterGenre2: '',
        picture: 'movie-4.png',
        alt: '',
        title: 'Movie 4',
        year: '',
        badge: '',
        duration: '',
        rating: '',
    },
    {
        id: 5,
        filterGenre1: '',
        filterGenre2: '',
        picture: 'movie-5.png',
        alt: '',
        title: 'Movie 5',
        year: '',
        badge: '',
        duration: '',
        rating: '',
    },
    {
        id: 6,
        filterGenre1: '',
        filterGenre2: '',
        picture: 'movie-6.png',
        alt: '',
        title: 'Movie 6',
        year: '',
        badge: '',
        duration: '',
        rating: '',
    },
    {
        id: 7,
        filterGenre1: '',
        filterGenre2: '',
        picture: 'movie-7.png',
        alt: '',
        title: 'Movie 7',
        year: '',
        badge: '',
        duration: '',
        rating: '',
    },
    {
        id: 8,
        filterGenre1: '',
        filterGenre2: '',
        picture: 'movie-8.png',
        alt: '',
        title: 'Movie 8',
        year: '',
        badge: '',
        duration: '',
        rating: '',
    },
    {
        id: 9,
        filterGenre1: '',
        filterGenre2: '',
        picture: '',
        alt: '',
        title: '',
        year: '',
        badge: '',
        duration: '',
        rating: '',
    },
    {
        id: 10,
        filterGenre1: '',
        filterGenre2: '',
        picture: '',
        alt: '',
        title: '',
        year: '',
        badge: '',
        duration: '',
        rating: '',
    },
    {
        id: 11,
        filterGenre1: '',
        filterGenre2: '',
        picture: '',
        alt: '',
        title: '',
        year: '',
        badge: '',
        duration: '',
        rating: '',
    },
    {
        id: 12,
        filterGenre1: '',
        filterGenre2: '',
        picture: '',
        alt: '',
        title: '',
        year: '',
        badge: '',
        duration: '',
        rating: '',
    },
    {
        id: 13,
        filterGenre1: '',
        filterGenre2: '',
        picture: '',
        alt: '',
        title: '',
        year: '',
        badge: '',
        duration: '',
        rating: '',
    },
    {
        id: 14,
        filterGenre1: '',
        filterGenre2: '',
        picture: '',
        alt: '',
        title: '',
        year: '',
        badge: '',
        duration: '',
        rating: '',
    },
    {
        id: 15,
        filterGenre1: '',
        filterGenre2: '',
        picture: '',
        alt: '',
        title: '',
        year: '',
        badge: '',
        duration: '',
        rating: '',
    },
    {
        id: 16,
        filterGenre1: '',
        filterGenre2: '',
        picture: '',
        alt: '',
        title: '',
        year: '',
        badge: '',
        duration: '',
        rating: '',
    },
    {
        id: 17,
        filterGenre1: '',
        filterGenre2: '',
        picture: '',
        alt: '',
        title: '',
        year: '',
        badge: '',
        duration: '',
        rating: '',
    },
    {
        id: 18,
        filterGenre1: '',
        filterGenre2: '',
        picture: '',
        alt: '',
        title: '',
        year: '',
        badge: '',
        duration: '',
        rating: '',
    },
    {
        id: 19,
        filterGenre1: '',
        filterGenre2: '',
        picture: '',
        alt: '',
        title: '',
        year: '',
        badge: '',
        duration: '',
        rating: '',
    },
    {
        id: 20,
        filterGenre1: '',
        filterGenre2: '',
        picture: '',
        alt: '',
        title: '',
        year: '',
        badge: '',
        duration: '',
        rating: '',
    },
    {
        id: 21,
        filterGenre1: '',
        filterGenre2: '',
        picture: '',
        alt: '',
        title: '',
        year: '',
        badge: '',
        duration: '',
        rating: '',
    },
    {
        id: 22,
        filterGenre1: '',
        filterGenre2: '',
        picture: '',
        alt: '',
        title: '',
        year: '',
        badge: '',
        duration: '',
        rating: '',
    },
    {
        id: 23,
        filterGenre1: '',
        filterGenre2: '',
        picture: '',
        alt: '',
        title: '',
        year: '',
        badge: '',
        duration: '',
        rating: '',
    },
    {
        id: 24,
        filterGenre1: '',
        filterGenre2: '',
        picture: '',
        alt: '',
        title: '',
        year: '',
        badge: '',
        duration: '',
        rating: '',
    },
    {
        id: 25,
        filterGenre1: '',
        filterGenre2: '',
        picture: '',
        alt: '',
        title: '',
        year: '',
        badge: '',
        duration: '',
        rating: '',
    },
    {
        id: 26,
        filterGenre1: '',
        filterGenre2: '',
        picture: '',
        alt: '',
        title: '',
        year: '',
        badge: '',
        duration: '',
        rating: '',
    },
    {
        id: 27,
        filterGenre1: '',
        filterGenre2: '',
        picture: '',
        alt: '',
        title: '',
        year: '',
        badge: '',
        duration: '',
        rating: '',
    },

    {
        id: 28,
        filterGenre1: '',
        filterGenre2: '',
        picture: '',
        alt: '',
        title: '',
        year: '',
        badge: '',
        duration: '',
        rating: '',
    },
    {
        id: 29,
        filterGenre1: '',
        filterGenre2: '',
        picture: '',
        alt: '',
        title: '',
        year: '',
        badge: '',
        duration: '',
        rating: '',
    },
    {
        id: 30,
        filterGenre1: '',
        filterGenre2: '',
        picture: '',
        alt: '',
        title: '',
        year: '',
        badge: '',
        duration: '',
        rating: '',
    },
];