let films = [
    {
        id: 1,
        filterGenre1: "",
        filterGenre2: "",
        picture: "",
        title: "",
        year: "",
        badge: "",
        duration: "",
        rating: "",
    },
    {
        id: 2,
        filterGenre1: "",
        filterGenre2: "",
        picture: "",
        title: "",
        year: "",
        badge: "",
        duration: "",
        rating: "",
    },
    {
        id: 3,
        filterGenre1: "",
        filterGenre2: "",
        picture: "",
        title: "",
        year: "",
        badge: "",
        duration: "",
        rating: "",
    },
    {
        id: 4,
        filterGenre1: "",
        filterGenre2: "",
        picture: "",
        title: "",
        year: "",
        badge: "",
        duration: "",
        rating: "",
    },
    {
        id: 5,
        filterGenre1: "",
        filterGenre2: "",
        picture: "",
        title: "",
        year: "",
        badge: "",
        duration: "",
        rating: "",
    },
    {
        id: 6,
        filterGenre1: "",
        filterGenre2: "",
        picture: "",
        title: "",
        year: "",
        badge: "",
        duration: "",
        rating: "",
    },
    {
        id: 7,
        filterGenre1: "",
        filterGenre2: "",
        picture: "",
        title: "",
        year: "",
        badge: "",
        duration: "",
        rating: "",
    },
    {
        id: 8,
        filterGenre1: "",
        filterGenre2: "",
        picture: "",
        title: "",
        year: "",
        badge: "",
        duration: "",
        rating: "",
    },
    {
        id: 9,
        filterGenre1: "",
        filterGenre2: "",
        picture: "",
        title: "",
        year: "",
        badge: "",
        duration: "",
        rating: "",
    },
    {
        id: 10,
        filterGenre1: "",
        filterGenre2: "",
        picture: "",
        title: "",
        year: "",
        badge: "",
        duration: "",
        rating: "",
    },
    {
        id: 11,
        filterGenre1: "",
        filterGenre2: "",
        picture: "",
        title: "",
        year: "",
        badge: "",
        duration: "",
        rating: "",
    },
    {
        id: 12,
        filterGenre1: "",
        filterGenre2: "",
        picture: "",
        title: "",
        year: "",
        badge: "",
        duration: "",
        rating: "",
    },
    {
        id: 13,
        filterGenre1: "",
        filterGenre2: "",
        picture: "",
        title: "",
        year: "",
        badge: "",
        duration: "",
        rating: "",
    },
    {
        id: 14,
        filterGenre1: "",
        filterGenre2: "",
        picture: "",
        title: "",
        year: "",
        badge: "",
        duration: "",
        rating: "",
    },
    {
        id: 15,
        filterGenre1: "",
        filterGenre2: "",
        picture: "",
        title: "",
        year: "",
        badge: "",
        duration: "",
        rating: "",
    },
    {
        id: 16,
        filterGenre1: "",
        filterGenre2: "",
        picture: "",
        title: "",
        year: "",
        badge: "",
        duration: "",
        rating: "",
    },
    {
        id: 17,
        filterGenre1: "",
        filterGenre2: "",
        picture: "",
        title: "",
        year: "",
        badge: "",
        duration: "",
        rating: "",
    },
    {
        id: 18,
        filterGenre1: "",
        filterGenre2: "",
        picture: "",
        title: "",
        year: "",
        badge: "",
        duration: "",
        rating: "",
    },
    {
        id: 19,
        filterGenre1: "",
        filterGenre2: "",
        picture: "",
        title: "",
        year: "",
        badge: "",
        duration: "",
        rating: "",
    },
    {
        id: 20,
        filterGenre1: "",
        filterGenre2: "",
        picture: "",
        title: "",
        year: "",
        badge: "",
        duration: "",
        rating: "",
    },
];